version: '3.8'
services:
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: virtuales
    networks:
      - my-network
    volumes:
      - ./sql-scripts:/docker-entrypoint-initdb.d
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./php:/var/www/html
    networks:
      - my-network
    depends_on:
      - db
networks:
  my-network:
    driver: bridge
